version: '3'

services:
  api:
    build: .
    ports:
      - "5001:5000"  # Changed from "5000:5000" to "5001:5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/blog-api
      - JWT_SECRET=your_secret_key_here_change_this_in_production
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: